### ISSUE TITLE
Use case question

### ISSUE THREAD

**Issue by jay-reynolds** [premolab/GeoMLE#2]
Would it be appropriate to use this method, for example, to estimate the intrinsic dimensionality of a word embedding?

**Comment by Tismoney** [comment]
Sure, you need to prepare the data into pandas DataFrame and run methods. The example of simple usage there is in [readme](https://github.com/premolab/GeoMLE/blob/master/README.md) or more complicated example in [ntb](https://github.com/premolab/GeoMLE/blob/master/paper/FinalNtb.ipynb).

If you have a lot samples and features, first of all try simple [MLE approach](https://github.com/premolab/GeoMLE/blob/master/geomle/mle.py) and then our [GeoMLE method](https://github.com/premolab/GeoMLE/blob/master/geomle/geomle.py) with parameter `ver = 'fastGeoMLE'`.
